image: openjdk:8

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind

stages:
  - test
  - build
  - build_image
  - depcheck

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - cache/caches/
    - cache/notifications/
    - cache/wrapper/

test:
  stage: test
  script:
    - ./gradlew --build-cache --gradle-user-home cache/ check

build:
  stage: build
  script:
    - ./gradlew --gradle-user-home cache/ publish -x test

depcheck:
  stage: depcheck
  script:
    - ./gradlew dependencyCheckAnalyze
  artifacts:
    when: always
    paths:
      - build/reports/dependency-check-report.html